# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bb1f3742ca3302cdc6a2de5ac02d85174a6c20fdd5c191c099912270c167c4fc4d74ce6d5c5cd6baab6a19ee446f7d0fcfd3aa35b35e059d3f2cdb18b9da1ff2

test:
  secret_key_base: cc9490f211bbb1d40ec13d4e1e496982592e28c1b86e6d6a0b139197c3dfa805395da9d8ec4c0aec70187880e8547c64353dac93d03749bf92b892ba956119f5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
